### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rachaelvp** [tlverse/tmlcimx2021-workshop#1]
General
- [x] Add Slack page @rachaelvp 
- [x] Decide with team where to put solutions to exercises — added solutions chapter @rachaelvp 

Roadmap materials
- [ ] Finalize materials for Monday, August 16 live session @rachaelvp — waiting to hear back from Alan and Mark
- [x] Create questions for roadmap exercises and add to chapter @rachaelvp 
- [ ] Draft possible solutions to roadmap exercises @rachaelvp — waiting to hear back from Alan and Mark

Cross-validation materials
- [ ] Finalize materials for Tuesday, August 17 live session (e.g., copy over cross-validation handbook chapter, create condensed version of cross-validation handbook chapter) @imalenica
- [ ] Draft possible solutions to cross-validation exercises @imalenica 

SL materials
- [x] Finalize materials for Wednesday, August 18 live session @rachaelvp
- [x] Draft possible solutions to SL exercises @rachaelvp

TMLE materials 
- [x] Finalize materials for Thursday, August 19 live session (e.g., copy over TMLE handbook chapter, create condensed version of TMLE handbook chapter) @jeremyrcoyle
- [ ] Draft possible solutions to TMLE exercises @jeremyrcoyle
